### ISSUE TITLE
LogFilePath is not configured correctly on every run

### ISSUE THREAD

**Issue by FinickyCode** [janegilring/Logman#3]
It appears that an underscore (_) is used as a separator in the LogFilePath property, however, the GetLogPath() function strips the underscore, resulting in the Test() reporting the property to be non-compliant, and Set() being executed on every run. If an underscore is not present in the LogFilePath property, similar behavior occurs.

Am I missing something in the configuration here? If not, are you happy to accept a pull request to address this, and also handle LogFilePaths with multiple underscores?

Given a configuration such as:

```
Configuration Test
{
    Import-DSCResource -ModuleName:'Logman' -Name:'Logman' -ModuleVersion:'1.1.1'
    Logman "Test"
    {
        DataCollectorSetName = 'Test'
        Ensure = 'Present'
        LogFilePath = 'c:\Config\Test_'
        XmlTemplatePath = "C:\Config\Test.xml"
    }
}
```

Each run will result in verbose output of:

```
[[Logman]Test] Updating LogFilePath c:\Config\Test to c:\Config\Test_
```

And Test-DscConfiguration reports the configuration to have drifted:

```
>Test-DscConfiguration -Detailed | fl *DesiredState


InDesiredState             : False
ResourcesInDesiredState    :
ResourcesNotInDesiredState : {[Logman]Test}
```

Given a configuration such as:

```
Configuration Test
{
    Import-DSCResource -ModuleName:'Logman' -Name:'Logman' -ModuleVersion:'1.1.1'
    Logman "Test"
    {
        DataCollectorSetName = 'Test'
        Ensure = 'Present'
        LogFilePath = 'c:\Config\Test'
        XmlTemplatePath = "C:\Config\Test.xml"
    }
}
```

Each run will result in verbose output of:

```
[[Logman]Test] Updating LogFilePath c:\Config\Test2018031319.tsv to c:\Config\Test
```

**Comment by janegilring** [comment]
Good catch, pull request merged
